#!/bin/bash

code --install-extension 4ops.terraform
code --install-extension aaron-bond.better-comments
code --install-extension adamzapasnik.elixir-test-explorer
code --install-extension ajshortt.tokyo-hack
code --install-extension alefragnani.bookmarks
code --install-extension alefragnani.numbered-bookmarks
code --install-extension alefragnani.project-manager
code --install-extension altimateai.vscode-altimate-mcp-server
code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension amillard98.specflow-tools
code --install-extension andys8.jest-snippets
code --install-extension antfu.slidev
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension ardenivanov.svelte-intellisense
code --install-extension asciidoctor.asciidoctor-vscode
code --install-extension astro-build.astro-vscode
code --install-extension asvetliakov.vscode-neovim
code --install-extension attilabuti.vscode-mjml
code --install-extension aws-scripting-guy.cform
code --install-extension bajdzis.vscode-database
code --install-extension bastienboutonnet.vscode-dbt
code --install-extension bierner.markdown-mermaid
code --install-extension bmarkovic.haproxy
code --install-extension bodil.file-browser
code --install-extension boto3typed.boto3-ide
code --install-extension bradlc.vscode-tailwindcss
code --install-extension burkeholland.simple-react-snippets
code --install-extension catppuccin.catppuccin-vsc
code --install-extension catppuccin.catppuccin-vsc-icons
code --install-extension chrischinchilla.vale-vscode
code --install-extension christian-kohler.npm-intellisense
code --install-extension cometeer.spacemacs
code --install-extension compilenix.vscode-zonefile
code --install-extension constneo.vscode-nushell-format
code --install-extension craigthomas.supersharp
code --install-extension cweijan.dbclient-jdbc
code --install-extension cweijan.vscode-database-client2
code --install-extension danielthielking.aws-cloudformation-yaml
code --install-extension davidanson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension dennismaxjung.vscode-dotnet-auto-attach
code --install-extension docker.docker
code --install-extension donjayamanne.githistory
code --install-extension donjayamanne.javadebugger
code --install-extension drewxs.tokyo-night-dark
code --install-extension dskwrk.vscode-generate-getter-setter
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension enkia.tokyo-night
code --install-extension esbenp.prettier-vscode
code --install-extension extr0py.vscode-relative-line-numbers
code --install-extension felipecaputo.git-project-manager
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension fireside21.cshtml
code --install-extension firsttris.vscode-jest-runner
code --install-extension florinpatrascu.vscode-elixir-snippets
code --install-extension formulahendry.docker-explorer
code --install-extension formulahendry.docker-extension-pack
code --install-extension formulahendry.dotnet-test-explorer
code --install-extension github.codespaces
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.remotehub
code --install-extension github.vscode-pull-request-github
code --install-extension golang.go
code --install-extension gp-pereira.refatorex
code --install-extension grafana.grafana-alloy
code --install-extension gruntfuggly.todo-tree
code --install-extension hangxingliu.vscode-nginx-conf-hint
code --install-extension hashicorp.terraform
code --install-extension hbenl.vscode-test-explorer
code --install-extension hediet.vscode-drawio
code --install-extension henriblancke.vscode-dbt-formatter
code --install-extension humao.rest-client
code --install-extension innoverio.vscode-dbt-power-user
code --install-extension ionide.ionide-fsharp
code --install-extension ipatalas.vscode-sprint-planner
code --install-extension jacobdufault.fuzzy-search
code --install-extension jakebecker.elixir-ls
code --install-extension jetpack-io.devbox
code --install-extension jmrog.vscode-nuget-package-manager
code --install-extension jorgeserrano.vscode-csharp-snippets
code --install-extension josefpihrt-vscode.roslynator
code --install-extension k--kato.docomment
code --install-extension k--kato.intellij-idea-keybindings
code --install-extension kahole.magit
code --install-extension karigari.chat
code --install-extension kddejong.vscode-cfn-lint
code --install-extension kevinrose.vsc-python-indent
code --install-extension kreativ-software.csharpextensions
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension lewisyliu.ef-core-snippets
code --install-extension littlefoxteam.vscode-python-test-adapter
code --install-extension llam4u.nerdtree
code --install-extension lovebird.better-comments-enhanced
code --install-extension magdalenalipka.tokyo-night-frameless
code --install-extension markwhen.markwhen
code --install-extension mhutchie.git-graph
code --install-extension mindaro-dev.file-downloader
code --install-extension mindaro.mindaro
code --install-extension mquandalle.graphql
code --install-extension mrmlnc.vscode-apache
code --install-extension ms-azuretools.vscode-azureresourcegroups
code --install-extension ms-azuretools.vscode-azurevirtualmachines
code --install-extension ms-azuretools.vscode-bicep
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csdevkit
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.dotnet-interactive-vscode
code --install-extension ms-dotnettools.vscode-dotnet-pack
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-dotnettools.vscodeintellicode-csharp
code --install-extension ms-edgedevtools.vscode-edge-devtools
code --install-extension ms-kubernetes-tools.vscode-aks-tools
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-mssql.data-workspace-vscode
code --install-extension ms-mssql.mssql
code --install-extension ms-mssql.sql-bindings-vscode
code --install-extension ms-mssql.sql-database-projects-vscode
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-powertoys
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.azure-repos
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-repositories
code --install-extension ms-vscode.remote-server
code --install-extension ms-vscode.test-adapter-converter
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msyrus.go-doc
code --install-extension mtxr.sqltools
code --install-extension mtxr.sqltools-driver-mysql
code --install-extension mtxr.sqltools-driver-pg
code --install-extension njpwerner.autodocstring
code --install-extension octref.vetur
code --install-extension oderwat.indent-rainbow
code --install-extension orta.vscode-jest
code --install-extension p1c2u.docker-compose
code --install-extension pantajoe.vscode-elixir-credo
code --install-extension patcx.vscode-nuget-gallery
code --install-extension pedromsluz.vscode-phoenix
code --install-extension peterj.proto
code --install-extension pflannery.vscode-versionlens
code --install-extension philipbe.theme-gray-matter
code --install-extension phoenixframework.phoenix
code --install-extension pivaszbs.svelte-autoimport
code --install-extension pmneo.tsimporter
code --install-extension premparihar.gotestexplorer
code --install-extension prisma.prisma
code --install-extension pulkitgangwar.nextjs-snippets
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension roblourens.vscode-nand2tetris-hdl
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension s1e2b3i4.onenord-vscode
code --install-extension samuel-pordeus.elixir-test
code --install-extension samuelcolvin.jinjahtml
code --install-extension saratravi.elixir-formatter
code --install-extension sdras.night-owl
code --install-extension sdras.vue-vscode-extensionpack
code --install-extension sdras.vue-vscode-snippets
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension skyapps.fish-vscode
code --install-extension somejack.csharp-code-snippets
code --install-extension sonarsource.sonarlint-vscode
code --install-extension spencer-farley.xunitsnippets
code --install-extension starkwang.markdown
code --install-extension steoates.autoimport
code --install-extension surrealdb.surrealql
code --install-extension svelte.svelte-vscode
code --install-extension sztheory.hex-lens
code --install-extension tamasfe.even-better-toml
code --install-extension task.vscode-task
code --install-extension thenuprojectcontributors.vscode-nushell-lang
code --install-extension tim-koehler.helm-intellisense
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension usernamehw.errorlens
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-spring-initializr
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vspacecode.vspacecode
code --install-extension vspacecode.whichkey
code --install-extension vue.volar
code --install-extension waderyan.gitblame
code --install-extension wayou.vscode-todo-highlight
code --install-extension wholroyd.jinja
code --install-extension william-voyek.vscode-nginx
code --install-extension willluke.nextjs
code --install-extension wix.vscode-import-cost
code --install-extension wmaurer.vscode-jumpy
code --install-extension xabikos.javascriptsnippets
code --install-extension xadillax.viml
code --install-extension xshrim.txt-syntax
code --install-extension yzhang.markdown-all-in-one
